#!/bin/bash
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color '#FF9E2F'
bspc config window_gap 0
bspc config click_to_focus true

bspc monitor HDMI-0 -d I II III IV 
bspc monitor DVI-I-1 -d V VI VII VIII

#bspc rule -a Gimp desktop=^8 follow=on state=floating
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a ffplay state=floating
bspc rule -a kruler state=floating
bspc rule -a Kupfer.py focus=on border=off
bspc rule -a Screenkey manage=off

setxkbmap 'es(dvp)' -option caps:swapescape
SXHKD_SHELL=/bin/bash sxhkd &
xsetroot -cursor_name left_ptr
wmname LG3D # fix for some Java apps
nitrogen --restore &

~/dotfiles/wtfd | ~/dotfiles/launch_bar.sh &

# Wait for bar to show up, so the tray does not end behind bar.
xdotool search --sync --name bar

trayer \
  --edge top \
  --align right \
  --transparent true \
  --alpha 0 \
  --tint 0x000000 \
  --widthtype pixel \
  --width 200 \
  --height 20 \
  --monitor 0 \
  --margin 158 &

compton --vsync opengl --xrender-sync --xrender-sync-fence -CG &
xset r rate 320 20 &

# Wait for trayer to show up, so no tray icons are missing
xdotool search --sync --classname trayer

# Execute local startup script.

# In that script you can launch applications like this:
#   dropboxd &

# Since trayer has already started up you can be sure no tray icons will be 
# missing.
if [ -f ~/.bspwmrc_local.sh ]; then
  . ~/.bspwmrc_local.sh
fi
