#!/bin/bash
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color '#7ddb58'
bspc config window_gap 4

bspc monitor HDMI-0 -d I II III IV 
bspc monitor DVI-I-1 -d V VI VII VIII

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on border=off
bspc rule -a Screenkey manage=off

setxkbmap 'es(dvp)' -option caps:swapescape
xsetroot -cursor_name left_ptr
wmname LG3D
sxhkd &
nitrogen --restore &
copyq &

~/dotfiles/wtfd | ~/dotfiles/launch_bar.sh &
trayer_after_bar() {
  until xdotool search --name bar > /dev/null; do
    sleep 0.05
  done

  trayer \
    --edge top \
    --align right \
    --transparent true \
    --alpha 0 \
    --tint 0x000000 \
    --widthtype pixel \
    --width 200 \
    --height 20 \
    --monitor 0 \
    --margin 138
}
trayer_after_bar &

compton --vsync opengl &
nm-applet &
